---

- name: Adding APT key
  apt_key:
    id: 7F0CEB10
    url: http://docs.mongodb.org/10gen-gpg-key.asc

- name: Add APT repository
  apt_repository:
    repo: "{{mongodb_repository}}"
    update_cache: yes

- name: Installing package
  apt:
    pkg: "{{ mongodb_package }}"
    state: present
